# Enable the Elite-C board
BOOTLOADER = atmel-dfu
MOUSEKEY_ENABLE = yes    # Mouse keys
RGBLIGHT_ENABLE = yes # Enable WS2812 RGB underlight.
RGB_MATRIX_ENABLE = no 
RGB_MATRIX_DRIVER = WS2812
RGB_MATRIX_KEYPRESSES = yes
OLED_ENABLE     = no
OLED_DRIVER     = SSD1306
LTO_ENABLE      = yes
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_i2c